name: BukkitAnimations
main: net.yzimroni.bukkitanimations.BukkitAnimationsPlugin
version: 0.1
description: BukkitAnimations Plugin
depend: [ProtocolLib]
authors: [yzimroni]
commands:
  bukkitanimations:
    description: BukkitAnimations command
    aliases: [ba, animation, animations]